# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='thumbnail',
            field=models.FileField(default=1, upload_to=login.models.get_upload_file_name),
            preserve_default=False,
        ),
    ]
