# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20160216_2012'),
        ('login', '0002_articles_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='user',
            field=models.ForeignKey(default=45456, on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserProfile'),
            preserve_default=False,
        ),
    ]
