# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0004_auto_20160221_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='user',
        ),
        migrations.AddField(
            model_name='articles',
            name='user_like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
