# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20160223_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name='data_published'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=login.models.get_upload_file_name),
        ),
        migrations.AlterField(
            model_name='articles',
            name='user_like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
