# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 22:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20160223_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='like',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='data_published'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=login.models.get_upload_file_name),
        ),
        migrations.AlterField(
            model_name='articles',
            name='user_like',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
